### ISSUE TITLE
Something went wrong rendering this element

### ISSUE THREAD

**Issue by aaronliu0130** [WolfPlugs/HolyNotes#8]
![image](https://github.com/WolfPlugs/HolyNotes/assets/11874211/ac17f121-1710-47e6-83f4-04bd0d098819)

I've updated it to the newest version.
<details>
	<summary>Log</summary>
	<pre>
13caabd38a2b1afb8c8b.js:218 ReferenceError: Timestamp is not defined
    at renderer.js?t=1686173075122}:1:9699
    at Array.map (<anonymous>)
    at I (renderer.js?t=1686173075122}:1:9649)
    at Sa (df6fb82e458a1febe2f1.js:1788:54)
    at gu (df6fb82e458a1febe2f1.js:1842:146)
    at Ic (df6fb82e458a1febe2f1.js:1835:89)
    at mc (df6fb82e458a1febe2f1.js:1835:17)
    at hc (df6fb82e458a1febe2f1.js:1834:867)
    at oc (df6fb82e458a1febe2f1.js:1831:642)
    at uc (df6fb82e458a1febe2f1.js:1832:49)
    at Fi (df6fb82e458a1febe2f1.js:1771:577)
    at lc (df6fb82e458a1febe2f1.js:1832:498)
    at t.flushSync (df6fb82e458a1febe2f1.js:1854:496)
    at o.toggleShow (df6fb82e458a1febe2f1.js:2861:67)
    at o.hide (df6fb82e458a1febe2f1.js:2860:853)
    at e.handleClick (df6fb82e458a1febe2f1.js:2858:726)
    at Object.Me (df6fb82e458a1febe2f1.js:1740:509)
    at je (df6fb82e458a1febe2f1.js:1740:663)
    at df6fb82e458a1febe2f1.js:1761:416
    at Ur (df6fb82e458a1febe2f1.js:1761:513)
    at Gr (df6fb82e458a1febe2f1.js:1761:927)
    at df6fb82e458a1febe2f1.js:1767:415
    at cc (df6fb82e458a1febe2f1.js:1832:267)
    at Le (df6fb82e458a1febe2f1.js:1739:624)
    at Yr (df6fb82e458a1febe2f1.js:1763:232)
    at Kt (df6fb82e458a1febe2f1.js:1746:858)
    at Zt (df6fb82e458a1febe2f1.js:1746:642)
    at HTMLDivElement.r (13caabd38a2b1afb8c8b.js:244:271)
(anonymous) @ 13caabd38a2b1afb8c8b.js:218
r.<computed> @ df6fb82e458a1febe2f1.js:9855
ds @ df6fb82e458a1febe2f1.js:1796
Es.o.componentDidCatch.n.callback @ df6fb82e458a1febe2f1.js:1797
Bo @ df6fb82e458a1febe2f1.js:1778
Tu @ df6fb82e458a1febe2f1.js:1826
Iu @ df6fb82e458a1febe2f1.js:1826
yu @ df6fb82e458a1febe2f1.js:1826
(anonymous) @ df6fb82e458a1febe2f1.js:1837
Oc @ df6fb82e458a1febe2f1.js:1838
uc @ df6fb82e458a1febe2f1.js:1832
Fi @ df6fb82e458a1febe2f1.js:1771
lc @ df6fb82e458a1febe2f1.js:1832
t.flushSync @ df6fb82e458a1febe2f1.js:1854
o.toggleShow @ df6fb82e458a1febe2f1.js:2861
o.hide @ df6fb82e458a1febe2f1.js:2860
e.handleClick @ df6fb82e458a1febe2f1.js:2858
Me @ df6fb82e458a1febe2f1.js:1740
je @ df6fb82e458a1febe2f1.js:1740
(anonymous) @ df6fb82e458a1febe2f1.js:1761
Ur @ df6fb82e458a1febe2f1.js:1761
Gr @ df6fb82e458a1febe2f1.js:1761
(anonymous) @ df6fb82e458a1febe2f1.js:1767
cc @ df6fb82e458a1febe2f1.js:1832
Le @ df6fb82e458a1febe2f1.js:1739
Yr @ df6fb82e458a1febe2f1.js:1763
Kt @ df6fb82e458a1febe2f1.js:1746
Zt @ df6fb82e458a1febe2f1.js:1746
r @ 13caabd38a2b1afb8c8b.js:244
13caabd38a2b1afb8c8b.js:218 [Replugged:Components:ErrorBoundary] ErrorBoundary caught an error ReferenceError: Timestamp is not defined
    at renderer.js?t=1686173075122}:1:9699
    at Array.map (<anonymous>)
    at I (renderer.js?t=1686173075122}:1:9649)
    at Sa (df6fb82e458a1febe2f1.js:1788:54)
    at gu (df6fb82e458a1febe2f1.js:1842:146)
    at Ic (df6fb82e458a1febe2f1.js:1835:89)
    at mc (df6fb82e458a1febe2f1.js:1835:17)
    at hc (df6fb82e458a1febe2f1.js:1834:867)
    at oc (df6fb82e458a1febe2f1.js:1831:642)
    at uc (df6fb82e458a1febe2f1.js:1832:49)
    at Fi (df6fb82e458a1febe2f1.js:1771:577)
    at lc (df6fb82e458a1febe2f1.js:1832:498)
    at t.flushSync (df6fb82e458a1febe2f1.js:1854:496)
    at o.toggleShow (df6fb82e458a1febe2f1.js:2861:67)
    at o.hide (df6fb82e458a1febe2f1.js:2860:853)
    at e.handleClick (df6fb82e458a1febe2f1.js:2858:726)
    at Object.Me (df6fb82e458a1febe2f1.js:1740:509)
    at je (df6fb82e458a1febe2f1.js:1740:663)
    at df6fb82e458a1febe2f1.js:1761:416
    at Ur (df6fb82e458a1febe2f1.js:1761:513)
    at Gr (df6fb82e458a1febe2f1.js:1761:927)
    at df6fb82e458a1febe2f1.js:1767:415
    at cc (df6fb82e458a1febe2f1.js:1832:267)
    at Le (df6fb82e458a1febe2f1.js:1739:624)
    at Yr (df6fb82e458a1febe2f1.js:1763:232)
    at Kt (df6fb82e458a1febe2f1.js:1746:858)
    at Zt (df6fb82e458a1febe2f1.js:1746:642)
    at HTMLDivElement.r (13caabd38a2b1afb8c8b.js:244:271) {componentStack: '\n    at I (replugged://plugin/dev.wolfplugs.HolyNo…cord.com/assets/df6fb82e458a1febe2f1.js:7285:659)'}
(anonymous) @ 13caabd38a2b1afb8c8b.js:218
r.<computed> @ df6fb82e458a1febe2f1.js:9855
mn @ (index):1
error @ (index):1
componentDidCatch @ (index):1
Es.o.componentDidCatch.n.callback @ df6fb82e458a1febe2f1.js:1797
Bo @ df6fb82e458a1febe2f1.js:1778
Tu @ df6fb82e458a1febe2f1.js:1826
Iu @ df6fb82e458a1febe2f1.js:1826
yu @ df6fb82e458a1febe2f1.js:1826
(anonymous) @ df6fb82e458a1febe2f1.js:1837
Oc @ df6fb82e458a1febe2f1.js:1838
uc @ df6fb82e458a1febe2f1.js:1832
Fi @ df6fb82e458a1febe2f1.js:1771
lc @ df6fb82e458a1febe2f1.js:1832
t.flushSync @ df6fb82e458a1febe2f1.js:1854
o.toggleShow @ df6fb82e458a1febe2f1.js:2861
o.hide @ df6fb82e458a1febe2f1.js:2860
e.handleClick @ df6fb82e458a1febe2f1.js:2858
Me @ df6fb82e458a1febe2f1.js:1740
je @ df6fb82e458a1febe2f1.js:1740
(anonymous) @ df6fb82e458a1febe2f1.js:1761
Ur @ df6fb82e458a1febe2f1.js:1761
Gr @ df6fb82e458a1febe2f1.js:1761
(anonymous) @ df6fb82e458a1febe2f1.js:1767
cc @ df6fb82e458a1febe2f1.js:1832
Le @ df6fb82e458a1febe2f1.js:1739
Yr @ df6fb82e458a1febe2f1.js:1763
Kt @ df6fb82e458a1febe2f1.js:1746
Zt @ df6fb82e458a1febe2f1.js:1746
r @ 13caabd38a2b1afb8c8b.js:244
e65eb65b59ef432ac98cb55b754b4798.webp:1          GET https://cdn.discordapp.com/avatars/423948925058416651/e65eb65b59ef432ac98cb55b754b4798.webp?size=80 404
Image (async)
I @ df6fb82e458a1febe2f1.js:1728
Ks @ df6fb82e458a1febe2f1.js:1814
Tc @ df6fb82e458a1febe2f1.js:1835
Ic @ df6fb82e458a1febe2f1.js:1835
mc @ df6fb82e458a1febe2f1.js:1835
hc @ df6fb82e458a1febe2f1.js:1834
uc @ df6fb82e458a1febe2f1.js:1831
Fi @ df6fb82e458a1febe2f1.js:1771
lc @ df6fb82e458a1febe2f1.js:1832
t.flushSync @ df6fb82e458a1febe2f1.js:1854
o.toggleShow @ df6fb82e458a1febe2f1.js:2861
o.hide @ df6fb82e458a1febe2f1.js:2860
e.handleClick @ df6fb82e458a1febe2f1.js:2858
Me @ df6fb82e458a1febe2f1.js:1740
je @ df6fb82e458a1febe2f1.js:1740
(anonymous) @ df6fb82e458a1febe2f1.js:1761
Ur @ df6fb82e458a1febe2f1.js:1761
Gr @ df6fb82e458a1febe2f1.js:1761
(anonymous) @ df6fb82e458a1febe2f1.js:1767
cc @ df6fb82e458a1febe2f1.js:1832
Le @ df6fb82e458a1febe2f1.js:1739
Yr @ df6fb82e458a1febe2f1.js:1763
Kt @ df6fb82e458a1febe2f1.js:1746
Zt @ df6fb82e458a1febe2f1.js:1746
r @ 13caabd38a2b1afb8c8b.js:244
21964eea44b1702146dd396badb25a44.webp:1          GET https://cdn.discordapp.com/avatars/812407508500480091/21964eea44b1702146dd396badb25a44.webp?size=80 404
Image (async)
I @ df6fb82e458a1febe2f1.js:1728
Ks @ df6fb82e458a1febe2f1.js:1814
Tc @ df6fb82e458a1febe2f1.js:1835
Ic @ df6fb82e458a1febe2f1.js:1835
mc @ df6fb82e458a1febe2f1.js:1835
hc @ df6fb82e458a1febe2f1.js:1834
uc @ df6fb82e458a1febe2f1.js:1831
Fi @ df6fb82e458a1febe2f1.js:1771
lc @ df6fb82e458a1febe2f1.js:1832
t.flushSync @ df6fb82e458a1febe2f1.js:1854
o.toggleShow @ df6fb82e458a1febe2f1.js:2861
o.hide @ df6fb82e458a1febe2f1.js:2860
e.handleClick @ df6fb82e458a1febe2f1.js:2858
Me @ df6fb82e458a1febe2f1.js:1740
je @ df6fb82e458a1febe2f1.js:1740
(anonymous) @ df6fb82e458a1febe2f1.js:1761
Ur @ df6fb82e458a1febe2f1.js:1761
Gr @ df6fb82e458a1febe2f1.js:1761
(anonymous) @ df6fb82e458a1febe2f1.js:1767
cc @ df6fb82e458a1febe2f1.js:1832
Le @ df6fb82e458a1febe2f1.js:1739
Yr @ df6fb82e458a1febe2f1.js:1763
Kt @ df6fb82e458a1febe2f1.js:1746
Zt @ df6fb82e458a1febe2f1.js:1746
r @ 13caabd38a2b1afb8c8b.js:244
acef90d41b4b7c4fad3edad6f45fe38f.webp:1          GET https://cdn.discordapp.com/avatars/689898980540153893/acef90d41b4b7c4fad3edad6f45fe38f.webp?size=80 404
Image (async)
I @ df6fb82e458a1febe2f1.js:1728
Ks @ df6fb82e458a1febe2f1.js:1814
Tc @ df6fb82e458a1febe2f1.js:1835
Ic @ df6fb82e458a1febe2f1.js:1835
mc @ df6fb82e458a1febe2f1.js:1835
hc @ df6fb82e458a1febe2f1.js:1834
uc @ df6fb82e458a1febe2f1.js:1831
Fi @ df6fb82e458a1febe2f1.js:1771
lc @ df6fb82e458a1febe2f1.js:1832
t.flushSync @ df6fb82e458a1febe2f1.js:1854
o.toggleShow @ df6fb82e458a1febe2f1.js:2861
o.hide @ df6fb82e458a1febe2f1.js:2860
e.handleClick @ df6fb82e458a1febe2f1.js:2858
Me @ df6fb82e458a1febe2f1.js:1740
je @ df6fb82e458a1febe2f1.js:1740
(anonymous) @ df6fb82e458a1febe2f1.js:1761
Ur @ df6fb82e458a1febe2f1.js:1761
Gr @ df6fb82e458a1febe2f1.js:1761
(anonymous) @ df6fb82e458a1febe2f1.js:1767
cc @ df6fb82e458a1febe2f1.js:1832
Le @ df6fb82e458a1febe2f1.js:1739
Yr @ df6fb82e458a1febe2f1.js:1763
Kt @ df6fb82e458a1febe2f1.js:1746
Zt @ df6fb82e458a1febe2f1.js:1746
r @ 13caabd38a2b1afb8c8b.js:244
6dd799ab3709eafa46067648da8ed386.webp:1          GET https://cdn.discordapp.com/avatars/897959442165932072/6dd799ab3709eafa46067648da8ed386.webp?size=80 404
Image (async)
I @ df6fb82e458a1febe2f1.js:1728
Ks @ df6fb82e458a1febe2f1.js:1814
Tc @ df6fb82e458a1febe2f1.js:1835
Ic @ df6fb82e458a1febe2f1.js:1835
mc @ df6fb82e458a1febe2f1.js:1835
hc @ df6fb82e458a1febe2f1.js:1834
uc @ df6fb82e458a1febe2f1.js:1831
Fi @ df6fb82e458a1febe2f1.js:1771
lc @ df6fb82e458a1febe2f1.js:1832
t.flushSync @ df6fb82e458a1febe2f1.js:1854
o.toggleShow @ df6fb82e458a1febe2f1.js:2861
o.hide @ df6fb82e458a1febe2f1.js:2860
e.handleClick @ df6fb82e458a1febe2f1.js:2858
Me @ df6fb82e458a1febe2f1.js:1740
je @ df6fb82e458a1febe2f1.js:1740
(anonymous) @ df6fb82e458a1febe2f1.js:1761
Ur @ df6fb82e458a1febe2f1.js:1761
Gr @ df6fb82e458a1febe2f1.js:1761
(anonymous) @ df6fb82e458a1febe2f1.js:1767
cc @ df6fb82e458a1febe2f1.js:1832
Le @ df6fb82e458a1febe2f1.js:1739
Yr @ df6fb82e458a1febe2f1.js:1763
Kt @ df6fb82e458a1febe2f1.js:1746
Zt @ df6fb82e458a1febe2f1.js:1746
r @ 13caabd38a2b1afb8c8b.js:244
e7c5dccc29146a4cad5d8a39681b50b3.webp:1          GET https://cdn.discordapp.com/avatars/771147161228148736/e7c5dccc29146a4cad5d8a39681b50b3.webp?size=80 404
	</pre>
</details>

**Comment by aaronliu0130** [comment]
Still happens.

**Comment by Wolfkid200444** [comment]
Fixed on commit e2f73f0

**Comment by aaronliu0130** [comment]
Ooh, of course it was timestamps. Thanks!

**Comment by aaronliu0130** [comment]
BTW do you have to manually update the store page?

**Comment by Wolfkid200444** [comment]
U will get the update on the updater
